apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DATABASE_HOST: {{ .Values.mysql.fullnameOverride }}
  DATABASE_NAME: {{ .Values.mysql.auth.database }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password }}
  DATABASE_USER: {{ .Values.mysql.auth.username }}