apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-generator
  namespace: user-generator
  labels:
    app: user-generator
spec:
  selector:
    matchLabels:
      app: user-generetor
  template:
    metadata:
      labels:
        app: user-generator
    spec:
      containers:
        - name: user-generator
          image: user-generator:latest
          imagePullPolicy: IfNotPresent
          args:
            - --kubeconfig .kube/config
            - --source ldap

---
apiVersion: v1
kind: Namespace
metadata:
  name: user-generator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-generator-sa
  namespace: user-generator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-generator-role
  namespace: user-generator
rules:
  - verbs:
      - create
    apiGroups:
      - iam.kubesphere.io
    resources:
      - users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-generator-rolebinding
  namespace: user-generator

subjects:
  - kind: ServiceAccount
    name: user-generator-sa
    namespace: user-generator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io/v1
  name: user-generator-role
