---
apiVersion: v1
kind: Namespace
metadata:
  name: user-generator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-generator-sa
  namespace: user-syncer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-generator-role
rules:
  - verbs:
      - create
    apiGroups:
      - iam.kubesphere.io
    resources:
      - users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-generator-rolebinding
  namespace: user-syncer

subjects:
  - kind: ServiceAccount
    name: user-syncer-sa
    namespace: user-syncer
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: user-syncer-role

---
apiVersion: batch/v1
kind: Job
metadata:
  name: user-generator
  namespace: user-syncer
spec:
  template:
    metadata:
      labels:
        app: user-generator
    spec:
      restartPolicy: OnFailure
      serviceAccountName: user-syncer-sa
      containers:
        - name: user-syncer
          image: user-generator:latest
          command:
            - user-syncer
            - --kubeconfig=InCluster
            - --source=ldap


