apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: user-generator
    spec:
      restartPolicy: OnFailure
      serviceAccountName: user-generator-sa
      containers:
        - name: user-generator
          image: {{ .Values.job.image }}
          command:
            - user-generator
            - --kubeconfig={{ .Values.job.command.kubeconfig }}
            - --source={{ .Values.job.command.source }}
          env:
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_HOST
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_NAME

