apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: user-generator
    spec:
      restartPolicy: OnFailure
      serviceAccountName: user-generator-sa
      containers:
        - name: user-generator
          image: {{ .Values.job.image }}
          command:
            - migrate -path=/usr/src/app/migrate/table -database="mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOST})/${DATABASE_NAME}" -verbose up &&
            - user-generator
            - --kubeconfig={{ .Values.job.command.kubeconfig }}
            - --source={{ .Values.job.command.source }}
            - --host={{ .Values.job.command.host }}
            - --user-path={{ .Values.job.command.userPath }}
            - --org-path={{ .Values.job.command.orgPath }}
          env:
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: {{ .Values.mysql.auth.rootPassword }}
            - name: DATABASE_HOST
              value: {{ .Values.mysql.fullnameOverride }}
            - name: DATABASE_NAME
              value: {{ .Values.mysql.auth.database}}

