mysql:
  auth:
    rootPassword: P@88w0rd
    database: ldap-manager
    username: chinamobile
    password: P@88w0rd
  fullnameOverride: mysql

job:
  image: user-syncer:latest
  imagePullPolicy: IfNotPresent
  command:
    kubeconfig: InCluster
    source: ldapManager
    host: 172.18.1.201:8080
    userPath: ldapManager/api/search/user/findAllUsers
    orgPath: ldapManager/api/search/org/findAllOrgs

