mysql:
  auth:
    rootPassword: P@88w0rd
    database: ldap-manager
    password: P@88w0rd
  fullnameOverride: mysql

operator:
  image: wenhaozhou/user-syncer-operator:v20221101-2

job:
  image: user-syncer:latest
  imagePullPolicy: IfNotPresent
  command:
    kubeconfig: InCluster
    source: ldapManager
    host: 172.18.1.201:8080
    userPath: ldapManager/api/search/user/findAllUsers
    orgPath: ldapManager/api/search/org/findAllOrgs

